apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: site-strooware
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
    - host: strooware.nl
      http:
        paths:
          - path: /
            backend:
              service:
                name: site-strooware
                port:
                  name: http
            pathType: Prefix
  tls:
    - hosts: [strooware.nl]
      secretName: site-strooware-cert
