/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx"
import { Route as SiteRouteImport } from "./routes/_site.tsx"
import { Route as SiteIndexRouteImport } from "./routes/_site.index.tsx"
import { Route as SiteTermsRouteImport } from "./routes/_site.terms.tsx"

const SiteRoute = SiteRouteImport.update({
  id: "/_site",
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof SiteIndexRoute
  "/terms": typeof SiteTermsRoute
}
export interface FileRoutesByTo {
  "/terms": typeof SiteTermsRoute
  "/": typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_site": typeof SiteRouteWithChildren
  "/_site/terms": typeof SiteTermsRoute
  "/_site/": typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/terms"
  fileRoutesByTo: FileRoutesByTo
  to: "/terms" | "/"
  id: "__root__" | "/_site" | "/_site/terms" | "/_site/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/_site": {
      id: "/_site"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_site/": {
      id: "/_site/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    "/_site/terms": {
      id: "/_site/terms"
      path: "/terms"
      fullPath: "/terms"
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.ts"
import type { createStart } from "@tanstack/solid-start"
declare module "@tanstack/solid-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
