name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    uses: strootje/strooweb-workflows/.github/workflows/build-and-deploy.yml@main
    permissions:
      contents: read
      packages: write
    with:
      IMAGE_NAME: strootje/site-strooware
      KUBE_NAMESPACE: strooware-public
    secrets: inherit